# Generated by Django 2.1 on 2018-10-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20181023_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/media/profile_pic/pic placeholder.png', null=True, upload_to='profile_pic'),
        ),
    ]
