# Generated by Django 2.1 on 2018-10-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20181023_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='./images/profile-pic.png/', null=True, upload_to='profile_pic'),
        ),
    ]
