# Generated by Django 2.1 on 2018-10-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20181024_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/profile_pic/pic placeholder.png/', null=True, upload_to='profile_pic'),
        ),
    ]
